name: demo
on:
  workflow_dispatch:
  push:
    branches:
      - 'demo**'
    tags-ignore:
      - '**'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          npm ci
          npm run build
      - name: minimum
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEMO }}
      - name: full options
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEMO }}
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0x0000ff
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
      - name: no detail
        uses: ./
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEMO }}
        with:
          nodetail: true
          title: "We did it!"
          color: 0xff91a4
      - name: markdown
        uses: ./
        with:
          webhook: ${{ secrets.DISCORD_DEMO }}
          nodetail: true
          title: New version of `software` is ready!
          description: |
            Version `1.2.3-alpha`
            Click [here](https://github.com/sarisia/actions-status-discord) to download!
