name: "run-releases-branch-remote"
on:
  workflow_dispatch:
  push:
    branches:
      - "releases/v1"
    tags-ignore:
      - "**"

jobs:
  run:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - windows-latest
          - windows-2022
          - windows-2019
          - macos-latest
          - macos-12
          - macos-11

    runs-on: ${{ matrix.os }}
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_VERBOSE }}
    steps:
      # checkout cannot detect job
      # - uses: actions/checkout@v2
      - name: run simple
        # do not reference as local action! (runs: ./)
        uses: sarisia/actions-status-discord@releases/v1
      - name: run full
        uses: sarisia/actions-status-discord@releases/v1
        with:
          status: Failure
          title: "${{ github.workflow }} - must failure"
          description: "testing `releases/v1` branch"
          nofail: false
          nodetail: false
          image: "https://user-images.githubusercontent.com/33576079/81886735-69e03f80-95d8-11ea-8828-fa10dda8afd1.png"
          color: 0xFFFFFF
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
      - name: run nodetail
        uses: sarisia/actions-status-discord@releases/v1
        with:
          status: Cancelled
          title: "${{ github.workflow }} - no details"
          nodetail: true
          nofail: false
