name: 'test cancel'
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: |
        npm ci
        npm run build
    - run: sleep 60
    - name: Test cancel
      uses: ./
      if: always()
      with:
        status: ${{ job.status }}
