name: 'test'
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: |
        npm ci
        npm run build
    - name: Test default
      uses: ./
      if: always()
    - run: sleep 1
    - name: Test webhook
      uses: ./
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK2 }}
    - run: sleep 1
    - name: Test job
      uses: ./
      if: always()
      with:
        job: 'Test actions-status-discord action'
    - run: sleep 1
    - name: Test description
      uses: ./
      if: always()
      with:
        description: Test description
    - run: sleep 1
    - name: Test nofail
      uses: ./
      if: always()
      with:
        status: ''
        nofail: 'false'
    - name: Test status
      uses: ./
      if: always()
      with:
        status: ${{ job.status }}    
